# 作者信息
author:
  -
    name: 顾重
    email: giantzero_x@163.com
    link: http://giant.top
    weibo: http://weibo.com/angelgzx
    github: http://github.com/GiantZero-x
    avator: /assets/img/avatar.jpg

# 站点信息
title: Welcome
description: 个人博客(基于jekyll);整理、记载关于生活，学习上的点点滴滴.
url: "http://giantr.top" # the base hostname & protocol for your site

# 阅读处理
encoding: utf-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 服务器选项
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# 默认模版
defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
      type: "posts" # 以前的 `post`， 在 Jekyll 2.2 里。
    values:
      layout: "post"

# 侧边栏过滤器
filter: 'category' # Choose 'tag' or 'category' as filter in sidebar.

# 输出url
permalink: /:year/:month/:day/:title.html

# Comment
# disqus_shortname: discussion_shortname

# google analytics 设置
google_analytics: UA-90644077-1
ga:
  -
    id: UA-90644077-1
    url: giantr.top

# 草稿
post:
  template: _post.txt
  extension: md


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-paginate
