# 作者信息 (调用时使用site.author.xxx
author:
    name: 顾重
    email: giantzero_x@163.com
    link: http://giant.top
    weibo: angelgzx
    github: GiantZero-x
    avatar: /assets/img/avatar.jpg

# 站点信息 (调用时使用site.xxx
title: 顾重の部落格
description: 个人博客(基于jekyll);整理、记载关于生活，学习上的点点滴滴.
url: http://giantr.top # the base hostname & protocol for your site
favicon: /assets/img/favicon.ico
backgroundImage: 1.jpg #在文章中简写为bg

# 阅读处理
encoding: utf-8
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 服务器选项
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# 默认模版
defaults:
  -
    scope:
      path: "" # 一个空的字符串代表项目中所有的文件
      type: "posts" # 以前的 `post`， 在 Jekyll 2.2 里。
    values:
      layout: "post"

# 侧边栏过滤器
filter: 'category' # 选择'tag'或者'category'来充当过滤器显示在左侧导航栏.

# 输出url
permalink: /:year/:month/:day/:title.html #文章路径会被分割为此种格式

# 评论
disqus_shortname: giantzero-x #注册disqus账号,选择安装在自己的站点

# google analytics 设置
google_analytics: UA-90644077-1 #注册Google账号,登陆Google Analytics设置自己的站点

# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-paginate #若安装jekyll-paginate插件则在此处进行修改
